// src/materials/chart/Chart.tsx
import type { MaterialWithLayout } from "@/types/Material";
import type { EChartsOptionV2 } from "@/types/EchartsOptionV2";
import { generateId } from "@/helpers/schema";
import { deepClone } from "@/utils/conversion";
import ChartComponent from "./Chart.vue";

const props = deepClone({
	option: {
		title: {
			show: true,
			text: "ECharts 入门示例",
		},
		tooltip: {
			show: true,
		},
		legend: {
			show: true,
			data: ["销量"],
		},
		xAxis: {
			data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"],
		},
		yAxis: {},
		series: [
			{
				name: "销量",
				type: "bar",
				data: [5, 20, 36, 10, 10, 20],
			},
		],
	} as EChartsOptionV2,
});
export type ChartProps = typeof props;
export type ChartEmitKey = "click";
export const Chart = (): MaterialWithLayout<ChartProps, ChartEmitKey> => ({
	version: "0.0.1",
	id: generateId(),
	key: "chart",
	title: "图表",
	actived: false,
	nestable: false,
	locked: false,
	hidden: false,
	selectable: true,
	moveable: true,
	resizable: true,
	autoReplace: false,
	autoLayout: false,
	layout: {
		snap: { v: [], h: [] },
		left: 0,
		top: 0,
		width: 300,
		height: 300,
	},
	props,
	state: {},
	watchers: [],
	dataSources: [],
	actions: [],
	emits: {
		click: { executeType: "concurrent", timeout: 0, actionsName: [] },
		mounted: { executeType: "concurrent", timeout: 0, actionsName: [] },
		beforeUnmount: { executeType: "concurrent", timeout: 0, actionsName: [] },
	},
	customProps: [],
	customEmits: [],
	propsExpression: {},
	stateExpression: {},
	components: [],
	render: (component) => <ChartComponent component={component} />,
});

// src/materials/chart/Chart.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, shallowRef, useTemplateRef, watch } from "vue";
import type { ComponentWithLayout } from "@/types/Component";
import type { ChartProps, ChartEmitKey } from "./Chart";
import { initComponent, triggerEmit } from "@/helpers/schema";
import * as echarts from "echarts";

interface Props {
	component: ComponentWithLayout<ChartProps, ChartEmitKey>;
}
const props = withDefaults(defineProps<Props>(), {});
const oChart = useTemplateRef("oChart");
const instance = shallowRef<echarts.ECharts | null>(null);
const payload = {};
initComponent(props.component);
onMounted(() => {
	triggerEmit(props.component.emits.mounted, props.component, payload);
	instance.value = echarts.init(oChart.value);
	instance.value.setOption({
		title: {
			text: "ECharts 入门示例",
		},
		tooltip: {},
		legend: {
			data: ["销量"],
		},
		xAxis: {
			data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"],
		},
		yAxis: {},
		series: [
			{
				name: "销量",
				type: "bar",
				data: [5, 20, 36, 10, 10, 20],
			},
		],
	});
	watch([() => props.component.layout.width, () => props.component.layout.height], () => {
		instance.value?.resize();
	});
});
onBeforeUnmount(() => triggerEmit(props.component.emits.beforeUnmount, props.component, payload));
</script>

<template>
	<div
		ref="oChart"
		class="chart"
		@click="triggerEmit(props.component.emits.click, props.component, payload, $event)"
	></div>
</template>
