// src/materials/dialog/Dialog.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, computed } from "vue";
import type { ComponentWithLayout } from "@/types/Component";
import type { TextProps, TextEmitKey } from "./Dialog";
import { initComponent, triggerEmit } from "@/helpers/schema";

interface Props {
	component: ComponentWithLayout<TextProps, TextEmitKey>;
}
const props = withDefaults(defineProps<Props>(), {});
const styleV2 = computed(() => ({
	color: props.component.props.fontColor,
	fontSize: props.component.props.fontSize + "px",
	fontStyle: props.component.props.fontStyle,
	fontWeight: props.component.props.fontWeight,
	fontFamily: props.component.props.fontFamily,
	textAlign: props.component.props.textAlign,
	textDecorationLine: props.component.props.textDecorationLine,
	lineHeight: props.component.props.lineHeight + "px",
	backgroundColor: props.component.props.backgroundColor,
	borderWidth: props.component.props.borderWidth + "px",
	borderColor: props.component.props.borderColor,
	borderStyle: props.component.props.borderStyle,
	borderRadius: props.component.props.borderRadius + "px",
}));
const payload = { content: "" };
initComponent(props.component);
onMounted(() => triggerEmit(props.component.emits.mounted, props.component, payload));
onBeforeUnmount(() => triggerEmit(props.component.emits.beforeUnmount, props.component, payload));
</script>

<template>
	<span
		class="text"
		:style="styleV2"
		@click="
			(payload.content = props.component.props.content),
				triggerEmit(props.component.emits.click, props.component, payload, $event)
		"
		@dblclick="
			(payload.content = props.component.props.content),
				triggerEmit(props.component.emits.dblclick, props.component, payload, $event)
		"
	>
		{{ props.component.props.content }}
	</span>
</template>

// src/materials/dialog/Dialog.tsx
import type { MaterialWithLayout } from "@/types/Material";
import { generateId } from "@/helpers/schema";
import { deepClone } from "@/utils/conversion";
import TextComponent from "./Dialog.vue";

const props = deepClone({
	content: "文本",
	fontColor: "#ffffff",
	fontSize: 16,
	fontStyle: "normal" as "normal" | "italic",
	fontWeight: "normal" as "normal" | "bold",
	fontFamily: "serif" as "serif",
	textAlign: "center" as "left" | "center" | "right",
	textDecorationLine: "none" as "none" | "overline" | "underline" | "line-through",
	lineHeight: 30,
	backgroundColor: "transparent",
	borderWidth: 0,
	borderColor: "transparent",
	borderStyle: "solid" as "solid" | "dashed" | "dotted",
	borderRadius: 0,
});
export type TextProps = typeof props;
export type TextEmitKey = "click" | "dblclick";
export const Text = (): MaterialWithLayout<TextProps, TextEmitKey> => ({
	version: "0.0.1",
	id: generateId(),
	key: "text",
	title: "文本",
	actived: false,
	nestable: false,
	locked: false,
	hidden: false,
	resizable: true,
	layout: {
		snap: { v: [], h: [] },
		left: 0,
		top: 0,
		width: 100,
		height: 30,
	},
	props,
	state: {},
	watchers: [],
	dataSources: [],
	actions: [],
	emits: {
		click: { executeType: "concurrent", timeout: 0, actionsName: [] },
		dblclick: { executeType: "concurrent", timeout: 0, actionsName: [] },
		mounted: { executeType: "concurrent", timeout: 0, actionsName: [] },
		beforeUnmount: { executeType: "concurrent", timeout: 0, actionsName: [] },
	},
	propsExpression: {},
	stateExpression: {},
	components: [],
	render: (component) => <TextComponent component={component} />,
});
